version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example123
      POSTGRES_DB: mydatabase
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script
    networks:
      - mynetwork

  web:
    build: .
    container_name: flask_app
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:example123@db:5432/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  app_postgres_data:
